projects:
  - name: MyProject
    descriptions: My Project descriptions
    environments:
      - slug: dev
        name: Development
        configs:
          - slug: development
          - slug: development_ruud
      - slug: ci
        name: Continues Integration
        configs:
          - slug: ci
          - slug: ci_bitbucket
          - slug: ci_github
      - slug: preview
        name: Preview
        configs:
          - slug: preview
      - slug: production
        name: Production
        configs:
          - slug: prod
          - slug: prod_eu
    secrets:
      - development:
          MY_SECRET: NOT_SO_SECRET_VALUE
          SECRET_EMPTY: ""
      - preview:
          MY_SECRET: NOT_SO_SECRET_VALUE
          SECRET_EMPTY: ""
