projects:
  - name: MyProject
    descriptions: My Project descriptions
    environments:
      - id: dev
        name: Development
        configs:
          - id: dev
          - id: dev_ruud
      - id: ci
        name: Continues Integration
        configs:
          - id: ci
          - id: ci_bitbucket
          - id: ci_github
      - id: stg
        name: Staging
        configs:
          - id: stg
      - id: prod
        name: Production
        configs:
          - id: prod
          - id: prod_eu
    secrets:
      dev:
        MY_SECRET: NOT_SO_SECRET_VALUE
        SECRET_EMPTY: ""
      ci_github:
        MY_SECRET: NOT_SO_SECRET_VALUE
        SECRET_EMPTY: ""
    integrations:
      - vercel:
          development: dev
          preview: stg
          production: prod
