projects:
  - name: MyProject
    descriptions: My Project descriptions
    environments:
      - slug: dev
        name: Development
        configs:
          - slug: dev
          - slug: dev_ruud
      - slug: ci
        name: Continues Integration
        configs:
          - slug: ci
          - slug: ci_bitbucket
          - slug: ci_github
      - slug: prod
        name: Production
        configs:
          - slug: prod
          - slug: prod_eu
    secrets:
      - config: dev
        secrets:
          MY_SECRET: NOT_SO_SECRET_VALUE
          SECRET_EMPTY: ""
      - config: ci_github
        secrets:
          MY_SECRET: NOT_SO_SECRET_VALUE
          SECRET_EMPTY: ""
